### ISSUE TITLE
TODO-List

### ISSUE THREAD

**Issue by Henrique-Navarro** [Henrique-Navarro/compile.io#2]
### Prioridades
- [ ] #5
   - [ ] questões
   - [ ] histórico 
- [x] ajustar fontes
- [x] ao fazer submissão e usuário acertar todas as questões lançar confeti
- [x] filtro por pontos
- [x] componentizar progress bar
- [ ] componentizar tudo
- [ ] corrigir profile page
- [x] Fazer Login (frontend tá meio bugado, pesquisar como faz)
- [x] Adicionar container JavaScript
- [x] remover repositório `questões` do projeto
- [x] adicionais mais conquistas e alimentar o frontend corretamente
- [x] Rota p/ cadastrar novo usuário
- [x] Lista de questões já resolvidas pelo usuário
- [x] Adicionar conquistas e trigger para ativá-las
- [x] Usuário ganha pontos ao acertar questões
- [x] Tela de perfil do usuário (quantidade de pontos, quantidade de questões resolvidas)
- [x] Criar ranking conforme pontos
- [x] Criar componente kit, deve ter uma imagem da linguagem de programação
   - [x] melhorar componente kit 
- [x] Adicionar botão ✨dica, cada questão terá sua dica, e somente será liberada, caso o usuário submeta seu código, quando o usuário passar o mouse, irá aparecer um flashcard com a dica
- [x] listagem de kits
- [ ] Adicionar 'travas' de segurança no código (interromper execução se demorar mais de 3s)
- [ ] Adicionar mais casos de código inseguro p/ mais linguagens de programação (bloquear leitura de arquivo, thread, etc)
- [ ] Ajustar conteúdo das questões, ajustar categorias (algoritmos, loops, ED, POO), ajustar kits, ajustar conquistas (buscar em outros sites para criar questões mais básicas)
   - [ ] remover `Objetivo`
   - [ ] `Descrição`: historinha / introdução da questão
   - [ ] `Tarefa`: oq deve ser feito + exemplos
   - [ ] remover `Explicação`
- [ ] Lançar exceptions personalizadas
- [ ] Criar testes unitários
- [ ] Padronizar todo código frontend/backend
- [x] Filtrar questões
- [ ] fazer tema claro / escuro
- [ ] adicionar sistema de questões favoritas

### Input
```
#php
$argv[1]

#js
process.argv[1]

#python
sys.argv[1]
```

#### Padrão API
- [ ] controller -> 1 operação
- [ ] handler -> faz validação e lança exception
- [ ] service -> 1 operação p/ repository
- [ ] retornar status ok
- [ ] `/save`. `/get-all`, `/get/{$id}`, `/update/{$id}`, `/delete{$id}`, `/delete-all`

#### Padrão estilos
```css
# cor de fundo
rgb(24, 20, 28);

# cor navbar
rgba(14,20,30,255)

# cor de box
rgb(32,36,44)

# cor de box interna
#2a2e38
```

### Se der tempo

- [x] Adicionar botão novo código que reseta todo o input do usuário
- [ ] Criar docker-compose na raiz do projeto p/ rodar frontend e backend (criar repositório `environment` p/ rodar todo o projeto)
- [x] Criar mais questões mais didáticas
- [x] Adicionar biografia no perfil do usuário
- [ ] Fazer testes de stress e limite (colocar código gigante, e identificar tamanho máximo GB)
- [ ] Execução de todos os casos de testes paralelamente (threads ou kubernets)
- [ ] Sistema mais robusto de testes (em vez de cadastrar o output na mão, executar o código correto, e pegar o output) (criar uma rota p/ criar questão, o body vai ter todas as informações, menos os outputs dos testes. Sistema vai pegar os inputs dos testes, executar o código e gerar o output, depois vai salvar a questão)

### Feitos

- [x] Fazer os arquivos de classe serem gerados dentro de tempfiles
- [x] Melhorar a arquitetura do projeto
- [x] Adicionar update, delete question
- [x] Histórico de submissões
- [x] CRUD user

### Adicionar futuramente

- [ ] MySQL
- [ ] Implementar métricas de análise do código
- [ ] Gráfico de desempenho no perfil do usuário
- [ ] Validar todas as rotas de GET e POST (em caso de POST, de algum objeto que tenha outro objeto como atributo tem que utilizar métodos setters)
- [ ] Adicionar Java (realizar processo de compilação)
- [ ] [ ] Adicionar feedback com chat GPT (frontend: adicionar um botão de ✨sugestão, backend: adicionar rota que retorna feedback)
- [ ] Integração com GitHub
- [ ] Modo debug, a cada linha executada, mostra a execução para o usuário

### Conquistas

- [ ] Consulta uma dica

**Comment by Henrique-Navarro** [comment]
Existem várias plataformas e ferramentas que você pode utilizar para análise de código em seu projeto. Algumas são focadas em análise estática (detectando problemas sem rodar o código), enquanto outras se concentram em testes dinâmicos ou análise de segurança. Aqui estão algumas opções que você pode considerar, dependendo de suas necessidades:

1. SonarQube
Descrição: SonarQube é uma plataforma popular de análise de qualidade de código. Ela fornece análise estática para detectar bugs, vulnerabilidades e "code smells" (mau cheiro de código). Suporta várias linguagens de programação.
Principais Funcionalidades:
Detecta problemas de segurança e vulnerabilidades.
Avalia a qualidade do código (complexidade, cobertura de testes, duplicação).
Suporta mais de 25 linguagens de programação.
Ideal para: Detecção de erros, bugs, e problemas de segurança em código.
Link: [SonarQube](https://www.sonarqube.org/)

2. Codacy
Descrição: Codacy é uma plataforma de análise de código que oferece feedback sobre qualidade de código, cobertura de testes, e complexidade. Ele pode ser integrado com repositórios como GitHub, GitLab e Bitbucket.
Principais Funcionalidades:
Suporte a mais de 40 linguagens de programação.
Análise estática de código e revisão de pull requests.
Feedback em tempo real para desenvolvedores.
Ideal para: Avaliação da qualidade do código e integração contínua.
Link: [Codacy](https://www.codacy.com/)

3. CodeClimate
Descrição: CodeClimate oferece análise estática e cobertura de código, permitindo que você entenda a qualidade do código e a saúde do seu repositório. Ele também fornece relatórios de segurança e ajuda a melhorar a legibilidade e a estrutura do código.
Principais Funcionalidades:
Análise de complexidade de código, duplicação, cobertura de testes e mais.
Suporta várias linguagens, incluindo Ruby, Python, JavaScript, entre outras.
Relatórios de segurança.
Ideal para: Integração contínua e feedback sobre a qualidade e segurança do código.
Link: [CodeClimate](https://codeclimate.com/)

4. Checkmarx
Descrição: Checkmarx é uma plataforma especializada em análise de segurança de código. Ele realiza análise estática de código-fonte para detectar vulnerabilidades de segurança.
Principais Funcionalidades:
Análise de segurança estática.
Detecção de vulnerabilidades como injeção de SQL, XSS, etc.
Suporta diversas linguagens e frameworks.
Ideal para: Identificação de vulnerabilidades de segurança e problemas de conformidade de código.
Link: [Checkmarx](https://www.checkmarx.com/)

5. LGTM
Descrição: LGTM (Looks Good To Me) é uma plataforma de análise de código que oferece feedback sobre qualidade e segurança. Ele possui integração com repositórios GitHub e GitLab.
Principais Funcionalidades:
Análise de código para encontrar vulnerabilidades, bugs e problemas de desempenho.
Feedback automático para pull requests.
Suporta múltiplas linguagens de programação.
Ideal para: Análise de código com foco em segurança e qualidade.
Link: [LGTM](https://lgtm.com/)

6. Snyk
Descrição: Snyk é uma plataforma focada na análise de segurança, particularmente voltada para vulnerabilidades em dependências de código. Ela pode ser usada para verificar bibliotecas de terceiros por problemas de segurança.
Principais Funcionalidades:
Verificação de vulnerabilidades em dependências.
Integrar com repositórios e pipelines de CI/CD.
Feedback sobre segurança de código.
Ideal para: Análise de segurança em dependências de código e contêineres.
Link: [Snyk](https://snyk.io/)

7. Pylint (para Python)
Descrição: Pylint é uma ferramenta de análise estática de código focada em Python. Ela ajuda a verificar erros no código, estilo de código, e problemas de design.
Principais Funcionalidades:
Análise de estilo de código (PEP8).
Detecção de erros de programação.
Suporte para personalização de regras.
Ideal para: Análise de qualidade de código em Python.
Link: Pylint

8. ESLint (para JavaScript)
Descrição: ESLint é uma ferramenta de análise estática de código voltada para JavaScript. Ela permite configurar e aplicar regras para garantir a qualidade e consistência do código JavaScript.
Principais Funcionalidades:
Análise de estilo e qualidade de código JavaScript.
Suporte para personalização e criação de regras.
Integração com editores de código e CI/CD.
Ideal para: Manter a qualidade e o estilo do código JavaScript.
Link: [ESLint](https://eslint.org/)

9. Clang (para C/C++)
Descrição: Clang é uma ferramenta de análise de código e compilador para C, C++ e outras linguagens de programação. Ele oferece diagnóstico de código-fonte e realiza verificações de qualidade e segurança.
Principais Funcionalidades:
Verificação de erros, avisos e análise de qualidade de código.
Suporte para a linguagem C/C++ e outras.
Ideal para: Análise de código em C/C++.
Link: Clang

10. DeepCode (agora parte do Snyk)
Descrição: DeepCode, agora adquirido pela Snyk, é uma ferramenta baseada em IA que analisa código para detectar problemas e sugerir melhorias.
Principais Funcionalidades:
Análise de código usando inteligência artificial para encontrar problemas.
Sugestões de correções baseadas em melhores práticas de codificação.
Ideal para: Feedback avançado, aproveitando IA para melhorar a qualidade do código.
Link: DeepCode

Como Integrar no seu Projeto:
Integração com Repositórios Git: Muitas dessas plataformas podem ser integradas diretamente ao seu repositório de código (GitHub, GitLab, Bitbucket). Isso permite que a análise de código seja executada automaticamente a cada novo commit ou pull request.
Ferramentas de CI/CD: Se você utiliza ferramentas de integração contínua (como Jenkins, Travis CI, GitHub Actions), muitas dessas plataformas oferecem integrações nativas para rodar a análise de código durante o pipeline de build.
Análises em Tempo Real: Ferramentas como o Codacy, SonarQube e LGTM fornecem feedback em tempo real, o que pode ser útil para ajudar os usuários a melhorar o código imediatamente enquanto programam.
Cada plataforma tem sua especialização, então escolher a melhor depende das necessidades do seu projeto (análise de segurança, performance, qualidade do código, etc.).

**Comment by Henrique-Navarro** [comment]
Aqui está uma lista das plataformas mencionadas anteriormente que oferecem APIs para você integrar a análise de código em seu projeto ou automatizar processos:

1. SonarQube
API Disponível: Sim, o SonarQube oferece uma API REST completa para integração. Através dessa API, você pode acessar diversos dados do projeto, como resultados da análise, informações sobre a qualidade do código, detalhes sobre problemas encontrados e muito mais.
Documentação: SonarQube Web API
Funcionalidades da API:
Buscar informações sobre projetos e análises.
Criar, listar e excluir análises.
Consultar métricas de qualidade do código.
Obter detalhes sobre problemas e vulnerabilidades.
2. Codacy
API Disponível: Sim, o Codacy oferece uma API REST para integrar e automatizar tarefas relacionadas à análise de código.
Documentação: Codacy API
Funcionalidades da API:
Obter informações sobre projetos e análises.
Consultar relatórios de qualidade de código.
Integrar com repositórios e pipelines CI/CD.
Gerenciar configurações de análise e regras de estilo de código.
3. CodeClimate
API Disponível: Sim, o CodeClimate oferece uma API para acessar e interagir com os dados das análises de código e integrar com outras ferramentas e sistemas.
Documentação: CodeClimate API
Funcionalidades da API:
Consultar dados sobre projetos e resultados de análise.
Obter informações sobre falhas, código duplicado, cobertura de testes e complexidade.
Integrar com repositórios GitHub e GitLab.
4. Checkmarx
API Disponível: Sim, Checkmarx oferece APIs que permitem a automação da análise de segurança de código e integração com outros sistemas.
Documentação: Checkmarx API
Funcionalidades da API:
Enviar códigos para análise de segurança.
Obter relatórios de vulnerabilidades e recomendações de correção.
Gerenciar projetos e integrações.
5. LGTM
API Disponível: Sim, LGTM oferece uma API para integração com repositórios e para acessar os resultados das análises de segurança e qualidade do código.
Documentação: LGTM API
Funcionalidades da API:
Consultar informações sobre análises de código e vulnerabilidades.
Obter relatórios detalhados e dados de qualidade.
Integrar com repositórios GitHub, GitLab e Bitbucket.
6. Snyk
API Disponível: Sim, Snyk oferece uma API robusta que permite realizar a análise de segurança de dependências e código.
Documentação: Snyk API
Funcionalidades da API:
Analisar vulnerabilidades em dependências de código.
Obter relatórios sobre vulnerabilidades de segurança.
Integrar com pipelines de CI/CD e repositórios.
Gerenciar tokens de autenticação e projetos.
7. Pylint (para Python)
API Disponível: Pylint não possui uma API nativa, mas é possível utilizar sua funcionalidade via linha de comando e integrar com outras ferramentas. Você pode executar o Pylint programaticamente usando a interface de linha de comando em um script Python.
Documentação: Pylint Documentation
Funcionalidades:
Executar verificações de estilo e qualidade de código no código Python.
Personalizar regras e integrar em scripts automatizados.
8. ESLint (para JavaScript)
API Disponível: ESLint oferece uma API de integração, onde você pode configurar e executar análises de código diretamente em seu ambiente de desenvolvimento ou via código.
Documentação: ESLint API
Funcionalidades da API:
Integrar diretamente no processo de build ou em ferramentas de CI/CD.
Analisar código JavaScript, identificar problemas de estilo e melhorar a qualidade.
Personalizar regras e configurar o comportamento da análise.
9. Clang (para C/C++)
API Disponível: Clang não possui uma API REST oficial, mas oferece uma série de interfaces e ferramentas de linha de comando que podem ser integradas ao seu processo de CI/CD ou outros sistemas de automação.
Documentação: Clang Documentation
Funcionalidades:
Análise de código C/C++ com ferramentas como Clang Static Analyzer.
Detecção de erros de sintaxe e complexidade de código.
Integrar com o processo de compilação para análise contínua de código.
10. DeepCode (agora parte do Snyk)
API Disponível: DeepCode foi adquirido pela Snyk, então as funcionalidades da DeepCode agora são acessíveis através da API do Snyk.
Documentação: Snyk API
Funcionalidades da API:
Usar IA para análise de código e obter feedback inteligente sobre vulnerabilidades e problemas no código.
Como Integrar com Sua Plataforma:
Para integrar qualquer uma dessas plataformas com seu sistema, você geralmente pode fazer chamadas à API REST da plataforma, enviando o código para análise e recebendo os relatórios com os resultados. Aqui estão algumas maneiras de integração:

Integração com Repositórios Git (GitHub, GitLab, Bitbucket): Muitas dessas plataformas oferecem integrações diretas com serviços de hospedagem de código. Você pode configurar para que a análise seja disparada automaticamente a cada push ou pull request.

Integração com CI/CD: Ferramentas de CI/CD como Jenkins, Travis CI, GitHub Actions ou GitLab CI podem ser configuradas para executar a análise de código como parte do pipeline de build. A maioria das plataformas mencionadas oferece integração com essas ferramentas.

Automação de Análises: Através das APIs, você pode automatizar o processo de análise para que o código submetido seja verificado em tempo real ou conforme necessário.

Essas APIs permitem uma análise de código contínua e personalizada, facilitando a integração com seu fluxo de trabalho e melhorando a qualidade do código automaticamente

**Comment by Henrique-Navarro** [comment]
Existem várias ferramentas que você pode usar para melhorar automaticamente um código, seja para melhorar a legibilidade, refatoração, otimização ou até correções de estilo. Aqui estão algumas opções que você pode considerar:

1. Codacy
Descrição: Codacy é uma plataforma que oferece feedback em tempo real sobre a qualidade do código. Ela analisa o código em busca de problemas de estilo, complexidade, bugs e vulnerabilidades, e sugere melhorias.
Funcionalidades:
Fornece sugestões automáticas de refatoração.
Sugestões de melhorias de estilo e boas práticas de programação.
Suporta várias linguagens, como Python, Java, JavaScript, Ruby, etc.
Link: [Codacy](https://www.codacy.com/)
2. SonarQube
Descrição: SonarQube é uma das ferramentas mais populares para análise estática de código. Ele verifica a qualidade do código, detectando problemas de estilo, complexidade, e segurança, e oferece sugestões para melhorar a qualidade do código.
Funcionalidades:
Sugestões de melhorias no código (refatoração e simplificação).
Identificação de vulnerabilidades de segurança.
Sugestões para reduzir a complexidade do código.
Link: [SonarQube](https://www.sonarqube.org/)
3. Refactoring.Guru
Descrição: Embora não seja uma ferramenta automática, Refactoring.Guru oferece uma excelente documentação e guias para refatoração de código. Ele ajuda desenvolvedores a melhorar seu código manualmente, explicando conceitos e padrões de refatoração.
Funcionalidades:
Oferece tutoriais e exemplos sobre como refatorar o código manualmente.
Fornece padrões de design e boas práticas para simplificar o código.
Link: [Refactoring.Guru](https://refactoring.guru/)
4. Prettier
Descrição: Prettier é uma ferramenta de formatação de código que pode melhorar a legibilidade do código automaticamente. Ela reformata o código para um estilo consistente, de acordo com as regras definidas.
Funcionalidades:
Reformatar automaticamente o código para seguir uma convenção de estilo.
Suporta várias linguagens, como JavaScript, TypeScript, Python, Java, HTML, CSS, etc.
Pode ser integrado com editores de código como VSCode, Sublime Text, etc.
Link: [Prettier](https://prettier.io/)
5. GitHub Copilot (com AI)
Descrição: GitHub Copilot, alimentado por inteligência artificial (IA), sugere melhorias no código enquanto você está programando. Ele pode sugerir trechos de código mais eficientes ou até mesmo refatorações para melhorar o desempenho.
Funcionalidades:
Sugestões automáticas de código enquanto você digita.
Oferece sugestões para melhorar a legibilidade e desempenho do código.
Capaz de sugerir trechos mais eficientes de código baseados em contexto.
Link: [GitHub Copilot](https://copilot.github.com/)
6. ReSharper (para C# e .NET)
Descrição: ReSharper é uma ferramenta de refatoração poderosa para o Visual Studio. Ela oferece sugestões para refatoração, corrigindo problemas de estilo, complexidade e eficiência no código C# e .NET.
Funcionalidades:
Refatoração automática de código.
Identificação de código redundante e sugestões para simplificação.
Análise de qualidade de código com sugestões de melhoria.
Link: [ReSharper](https://www.jetbrains.com/resharper/)
7. PyCharm (para Python)
Descrição: PyCharm, uma IDE para Python da JetBrains, oferece ferramentas de refatoração integradas que podem sugerir e aplicar melhorias no código Python, como simplificação de estruturas, remoção de código redundante, etc.
Funcionalidades:
Refatoração automática para simplificar e melhorar o código.
Sugestões de boas práticas para Python.
Análise de código para identificar melhorias.
Link: [PyCharm](https://www.jetbrains.com/pycharm/)
8. Tern (para JavaScript)
Descrição: Tern é uma ferramenta para análise estática de código JavaScript. Ela pode ser integrada com editores de código como Sublime Text, Atom, ou Vim para sugerir melhorias e refatorações.
Funcionalidades:
Sugestões automáticas de refatoração para JavaScript.
Análise de código para identificar áreas de melhoria.
Link: [Tern](http://ternjs.net/)
9. ESLint (para JavaScript)
Descrição: ESLint é uma ferramenta de análise de código JavaScript que ajuda a identificar e corrigir problemas de estilo, bugs e até vulnerabilidades no código. Além disso, ele sugere melhorias no estilo e na estrutura do código.
Funcionalidades:
Sugestões de refatoração baseadas em regras configuráveis.
Ajuda a melhorar a legibilidade e manutenção do código JavaScript.
Link: [ESLint](https://eslint.org/)
10. Clang-Tidy (para C/C++)
Descrição: Clang-Tidy é uma ferramenta de refatoração e verificação de código para C e C++. Ele oferece uma série de "checks" que podem ser usados para melhorar o código, tornando-o mais eficiente e legível.
Funcionalidades:
Refatoração automática e sugestões de melhoria para C/C++.
Sugestões de otimização de código e detecção de problemas de estilo.
Link: Clang-Tidy
11. Automated Refactoring Tools (para várias linguagens)
Algumas ferramentas oferecem refatoração automática para várias linguagens de programação, como JetBrains IntelliJ IDEA para Java, PHPStorm para PHP, e Visual Studio Code com extensões específicas.
Funcionalidades gerais:
Refatoração automática com base nas melhores práticas.
Identificação de código morto, duplicado ou ineficiente.
Melhorias no desempenho e legibilidade do código.
Como Integrar essas Ferramentas em seu Fluxo de Trabalho:
IDE/Editor de Código: Muitas dessas ferramentas podem ser integradas diretamente ao seu editor de código ou IDE (por exemplo, GitHub Copilot no VSCode, PyCharm para Python, ESLint no VSCode ou Sublime Text).
CI/CD: Você pode configurar essas ferramentas em seu pipeline de CI/CD para que a refatoração e a análise de código sejam feitas automaticamente sempre que você fizer um commit.
Automação: Algumas dessas ferramentas, como Prettier e ESLint, podem ser configuradas para executar automaticamente em seu código sempre que você salvar ou enviar o código para o repositório.
Resumo:
Para refatoração automática de código: Codacy, SonarQube, GitHub Copilot, ReSharper.
Para melhorar estilo e legibilidade: Prettier, ESLint, PyCharm.
Para análise de qualidade de código e segurança: SonarQube, Codacy, Checkmarx.
Essas ferramentas vão ajudar a melhorar o código de várias maneiras, seja com sugestões de estilo, refatoração, ou até correção de problemas de segurança e desempenho.
